alias: ESP E-ink - Dynamiczna prognoza pogody (co 2h) - FINAL
description: >-
  Pobiera godzinową prognozę i wyświetla co 2. przyszłą prognozę. Finalna
  działająca wersja.
triggers:
  - minutes: /30
    trigger: time_pattern
  - event: start
    trigger: homeassistant
conditions: []
actions:
  - data:
      type: hourly
    target:
      entity_id: weather.home
    response_variable: hourly_forecast
    action: weather.get_forecasts
  - variables:
      raw_data: |
        {{ hourly_forecast['weather.home'].forecast 
          if hourly_forecast is defined and 'weather.home' in hourly_forecast 
          else [] }}
      current_condition: "{{ states('weather.home') }}"
      current_temp: "{{ state_attr('weather.home', 'temperature') }}"
  - variables:
      slot_1_data: |
        {% if raw_data | length > 1 %}
          {% set f = raw_data[1] %}
          {% set dt = f.datetime | as_datetime %}
          {{ dt.astimezone().strftime('%H:00') }}|{{ f.condition }}|{{ f.temperature }}
        {% else %}
          {{ (now() + timedelta(hours=2)).strftime('%H:00') }}|{{ current_condition }}|{{ current_temp }}
        {% endif %}
      slot_2_data: |
        {% if raw_data | length > 3 %}
          {% set f = raw_data[3] %}
          {% set dt = f.datetime | as_datetime %}
          {{ dt.astimezone().strftime('%H:00') }}|{{ f.condition }}|{{ f.temperature }}
        {% else %}
          {{ (now() + timedelta(hours=4)).strftime('%H:00') }}|{{ current_condition }}|{{ current_temp }}
        {% endif %}
      slot_3_data: |
        {% if raw_data | length > 5 %}
          {% set f = raw_data[5] %}
          {% set dt = f.datetime | as_datetime %}
          {{ dt.astimezone().strftime('%H:00') }}|{{ f.condition }}|{{ f.temperature }}
        {% else %}
          {{ (now() + timedelta(hours=6)).strftime('%H:00') }}|{{ current_condition }}|{{ current_temp }}
        {% endif %}
      precipitation_2h: >
        {% set total_precip = namespace(sum=0) %} {% set now_ts =
        now().timestamp() %} {% set limit_ts = (now() +
        timedelta(hours=2)).timestamp() %} {% for entry in raw_data if
        entry.datetime is defined %}
          {% set entry_ts = (entry.datetime | as_datetime).timestamp() %}
          {% if entry_ts > now_ts and entry_ts <= limit_ts %}
            {% set total_precip.sum = total_precip.sum + (entry.precipitation | float(0)) %}
          {% endif %}
        {% endfor %} {{ "%.1f" | format(total_precip.sum) }}
  - data:
      entity_id: input_text.eink_forecast_12_wu
      value: "{{ slot_1_data }}"
    action: input_text.set_value
  - data:
      entity_id: input_text.eink_forecast_16_wu
      value: "{{ slot_2_data }}"
    action: input_text.set_value
  - data:
      entity_id: input_text.eink_forecast_20_wu
      value: "{{ slot_3_data }}"
    action: input_text.set_value
  - data:
      entity_id: input_text.eink_precipitation_forecast
      value: "{{ precipitation_2h }}"
    action: input_text.set_value
mode: single
